# Generated by Django 3.2.4 on 2021-06-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio_ciudadela',
            name='numParques',
            field=models.CharField(choices=[('1', '1 Parque'), ('2', '2 Parques'), ('3', '3 Parques'), ('4', '4 Parques'), ('5', '5 Parques'), ('6', '6Parques')], max_length=30),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='tipo',
            field=models.CharField(choices=[('Urbana', '1'), ('Rural', '2')], max_length=30),
        ),
    ]
